### PR TITLE
Make RGBASM overwrite output files atomically

### LINKED ISSUE #446: RGBASM can fail but output a corrupted .o file
Errors in RGBASM during generation of the output file (such as #445) still cause the output file to be created, but it's only partial, and can cause RGBLINK to softlock (like in #422).
This will play bad with build systems such as Make.

What's best, deleting that partial file, or storing it in memory and only overwriting the output file on completion?

### PR DESCRIPTION
**Pull request by ISSOtm**
Fixes #446.

I am not sure this is the best (in cases where the target directory is not writable but the target file is), but maybe this can be toggled via a flag, for example.
The temporary file is kept on failures, so the user could still try doing something with it. Is it a good idea?

### CODE REVIEW

**Comment by aaaaaa123456789** [comment]
Have you tested this on Windows? You're using `<unistd.h>`.

(That being said, "keep temporary files" is generally a flag for the odd case you need them, because 99% of the time, you don't.)

**Comment by AntonioND** [comment]
I'm thinking... what about just having a checksum at the end of the object file? Or in the header, it doesn't matter. This would be useful not only for the case in which the object file isn't written completely, but for any case in which the object file is corrupted.

**Comment by ISSOtm** [comment]
That doesn't sound like a bad idea, but not creating the file at all is required for example to play nice with `make`.

I tested this under Wine, and it appears the call to `mkstemp` fails with EEXIST.
I'm starting to think it might be a better idea to create and write to the file in RAM, then atomically copy it—but how to do that?

**Comment by aaaaaa123456789** [comment]
How would you atomically write to disk in the first place? That doesn't sound like something possible.

**Comment by AntonioND** [comment]
> How would you atomically write to disk in the first place? That doesn't sound like something possible.

By writing to a temporary file and renaming it, I guess. Where have I heard that before...? xD

**Comment by aaaaaa123456789** [comment]
That's a completelt different thing. `tmpfile()` should portably give a temporary file, but renaming/moving it isn't easy.

**Comment by ISSOtm** [comment]
Linux has a functionality that seems perfect for this, which is creating a file in the system that is not accessible from anywhere:
```C
char path[PATH_MAX];
fd = open("/path/to/dir", O_TMPFILE | O_RDWR, S_IRUSR | S_IWUSR);

/* File I/O on 'fd'... */

snprintf(path, PATH_MAX, "/proc/self/fd/%d", fd);
linkat(AT_FDCWD, path, AT_FDCWD, "/path/for/file", AT_SYMLINK_FOLLOW);
// or more simply `linkat(fd, "", AT_FDCWD, "/path/for/file", AT_EMPTY_PATH);`
```
But of course:
> The `O_DIRECT`, `O_NOATIME`, `O_PATH`, and **`O_TMPFILE`** flags are Linux-specific. One must define `_GNU_SOURCE` to obtain their definitions.

----

`tmpfile()` should be as portable as `mkstemp`—POSIX 2001— but I do not know how I could obtain the path from a `tmpfile`-created file.

Anyways, maybe the problem we're trying to solve is not writing the file atomically, but instead writing to a temporary file, so failure mid-assembly doesn't produce a half-baked file, right? In that case, `tmpfile` followed by some sort of copy should be enough, right?

**Comment by bentley** [comment]
> I tested this under Wine, and it appears the call to `mkstemp` fails with EEXIST.

That just means there aren’t enough `X`, doesn’t it? Does it still fail if you add more?

**Comment by ISSOtm** [comment]
I re-checked, and the failing call seems to be `rename`, actually? I was pretty sure it was `mkstemp` but whatever.

```
error: Couldn't create object file (temp file kept as /tmp/rgbasm_tmpqPB8SV): File exists
```
According to its man page, `rename` should never fail with EEXIST, so what gives?

**Comment by pinobatch** [comment]
The semantics of [`rename` under Windows](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/rename-wrename?view=vs-2019) differ from POSIX. Whereas POSIX specifies "replace if exists," Windows has "fail if exists." For the semantics you appear to want, use [`MoveFileEx(oldname, newname, MOVEFILE_WRITE_THROUGH|MOVEFILE_REPLACE_EXISTING)`](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-movefileexa).

**Comment by aaaaaa123456789** [comment]
Replacing a file can _always_ fail. What if the file exists, but you don't have permissions to write it, or to delete it and recreate it?

**Comment by pinobatch** [comment]
Replacing a file can either fully succeed or fully fail. We don't want it to half fail and half succeed. We want to detect this failure in order to return a nonzero exit code and leave unchanged what was there.

**Comment by ISSOtm** [comment]
Quoting POSIX:

>        If the rename() function fails for any reason other than `[EIO]`, any
>        file named by `new` shall be unaffected.

EIO being "A physical I/O error has occurred", which we won't even try to begin to handle. :p
I don't know if Windows' `MoveFileEx` has the same semantics, the page does not seem to mention it.

Also, I'm not sure how to handle calling `MoveFileEx` on Windows only. Should a specific `#ifdef` be used, or something else? cc @AntonioND

**Comment by AntonioND** [comment]
I guess that if there is no reliable way to do this in a cross-platform way, ifdefs are not a bad idea.

**Comment by aaaaaa123456789** [comment]
If all you want is to avoid the "incomplete file" problem, just write a dummy header like `BAD6`, and fix that to `RGB6` when you finish writing the rest of the file.

**Comment by AntonioND** [comment]
> If all you want is to avoid the "incomplete file" problem, just write a dummy header like `BAD6`, and fix that to `RGB6` when you finish writing the rest of the file.

``make`` will still detect that the object file has been generated and it won't try to regenerate it.

**Comment by aaaaaa123456789** [comment]
I think you can expect some minimal user intelligence if you get an error like "malformed object file; please rebuild".

**Comment by ISSOtm** [comment]
It wouldn't work for example if writing to a pipe.

**Comment by aaaaaa123456789** [comment]
If you're writing to stdout, build the file in memory and then push it out all at once. You have to have enough memory in that case anyway, after all...

**Comment by ISSOtm** [comment]
It can work even with named pipes (which you seem to be able to write to)

**Comment by aaaaaa123456789** [comment]
GCC requires files to be seekable (you'll get an ugly error otherwise); I don't see why adding the same requirement to RGBDS would be too problematic. Writing to stdout is an exception, but you can detect that. Any weird combination can be handled by writing to stdout and using the shell to redirect that.

**Comment by ISSOtm** [comment]
This is able to compile pokecrystal via the mingw32 build running via Wine, so I think this is fixed.
The temp files are kept on errors, but this is partially because any of the intermediate functions in `out_WriteObject` can just error out and the temp file will not be overwritten.

Further, I'm actually noticing the `open_memstream` function, which would allow writing to a temp file *in memory*, and that *would grow as needed*. If it works under Windows, this would be a better solution, wouldn't it?

**Comment by aaaaaa123456789** [comment]
Having to use mingw32 makes the code by definition not portable. Doesn't sound like a good idea.

**Comment by ISSOtm** [comment]
Sorry, I meant that I *tested* this with the mingw32 build, as I do not have a Windows box that would be able to test this on Windows proper.

**Comment by aaaaaa123456789** [comment]
My point is that you're relying on a mingw32 library (`unistd.h`).

**Comment by ISSOtm** [comment]
That point is valid, but I don't think we intend to support directly compiling on Windows. (cc @AntonioND)

Here are ways to (more or less) atomically write the target file:
- Current implementation: *Create the file with `mkstemp` and `rename`(-ish) it*
  Relies on `unistd` because `mkstemp` returns a file descriptor. It's POSIX but not Windows. Keeps the file around if the program terminates (think `errx`).
- Just tested: *Open the file with `open_memstream` (POSIX 2008) and write the buffer to the file (in a single `fwrite` call)*
  The `fwrite` can fail in the middle, producing a truncated file. But that doesn't matter anyways, because this function is not supported by `mingw`.
- *Get a temporary file name using `tempnam` or similar and copy it at the end*
  The copy can also fail in the middle. This is also vulnerable to a TOCTTOU (`fopen` does not support anything resembling `O_EXCL`, it seems), which would be relevant if for example doing a parallel `make` with a lot of RGBASM invocations.
- *Create a temporary file with `tmpfile` and copy it at the end*
  The copy can yet again fail in the middle. Moreso because we have to perform the copy block by block, since we don't have a buffer containing the whole file data (unlike `open_memstream`)

Writing a temporary bad header and erroring out when encountering it would require build systems to remove that faulty file, which is going to be annoying. That's why I want to avoid it.

**Comment by aaaaaa123456789** [comment]
I'd say that for the _very rare_ case of getting a broken file, requiring the user to do `make clean` manually isn't too troublesome.

**Comment by AntonioND** [comment]
I don't know, to be honest. I see the value in having the files be ok or to just not be there, but it's such a marginal benefit that I don't know what to think about it.

What do things like GCC or Clang do?

**Comment by aaaaaa123456789** [comment]
GCC and Clang are already non-portable, I believe. (They support multiple OSes, but explicitly, by force of `#ifdef`.) On the other hand, it's very hard to get GCC to produce partial output.

But I believe it just leaves temporary garbage if that happens. I've definitely seen some .tmp<something>.s leftovers.

**Comment by AntonioND** [comment]
Sure, but what I was thinking is that it's usually better to follow the behaviour of preexisting tools. Compilers, build systems, etc, have evolved simultaneously so they tend to work best with tools that behave in a similar way.

**Comment by ISSOtm** [comment]
I did some additional testing on my end, and this build seems at least to match current master's behavior. If this seems good, then I will merge. Hopefully this can help clean up further efforts..!!

**Comment by ISSOtm** [comment]
Wrong tab, I wanted to do this on another one... Should I revert?

File: src/asm/output.c [hunk 1]
```diff
@@ -532,13 +549,25 @@ static void checksectionoverflow(uint32_t delta_size)
  */
 void out_WriteObject(void)
 {
+	/* Write to a temporary file in the target's folder */
+	char *objectNameCopy = strdup(tzObjectname);
+	char const *dirPath = dirname(objectNameCopy);
+	char tmpFileName[strlen(dirPath) + 1 + 16 + 1];
+
+	sprintf(tmpFileName, "%s/rgbasm_tmpXXXXXX", dirPath);
```
Comment (AntonioND) [inline src/asm/output.c]: ``snprintf``?

**Comment by AntonioND** [comment]
About reverting, I don't know.

**Comment by ISSOtm** [comment]
One of the reasons why I'd want to revert is because I like this solution less than the `tmpfile`+copy one, which I have implemented on a local branch.

File: src/asm/output.c (hunk 1 above)
Comment (ISSOtm) [reply src/asm/output.c]: Guaranteed not to overflow given the buffer's size.

Comment (aaaaaa123456789) [reply src/asm/output.c]: Technically, given that the buffer is a VLA, it's not even guaranteed to exist.

**Comment by AntonioND** [comment]
Well, then revert it. I'm not too fond of the solution here, to be fair. This is not too critical or getting in the way of other PRs.

File: src/asm/output.c (hunk 1 above)
Comment (AntonioND) [reply src/asm/output.c]: Even if it was correct, I think that adding numbers by hand makes it quite fragile, so it's better to be defensive and use ``snprintf`` unless there is a really good reason not to do it.

**Comment by ISSOtm** [comment]
What about solution 4, creating a file with `tmpfile` and copying it? If the copy fails, the partial file can be deleted, and the temp file will be destroyed on exit.

**Comment by AntonioND** [comment]
I actually think that the general idea of the fix you merged is fine. I just think there are a couple of things that can be tweaked. For example, rather than having a macro called rename I think it's better to have one function and to put inside the ifdefs that depend on the OS.

Also, maybe you can call ``atexit()`` with a function that does the cleanup of the temporary file. It probably won't work in all cases, but I'd say that it's good enough.

**Comment by ISSOtm** [comment]
I thought about using `atexit()` as well, but then that started to look like over-engineering vs. `tmpfile`+copy.
