### PR TITLE
Make RGBDS behave identically whether writing a .o

### LINKED ISSUE #404: test/asm/undefined-dot.asm fails when no output file is provided
This breaks `update-refs.sh`

### PR DESCRIPTION
**Pull request by ISSOtm**
Some errors are only tripped in `out_WriteObject`, which was basically a stub when `-o` wasn't specified. Now, instead, the function is ran but all output functions are skipped.

Fixes #404.

### CODE REVIEW

**Comment by ISSOtm** [comment]
CI failed from timing out (again). Bumping to restart it.

**Comment by ISSOtm** [comment]
And again...

File: src/asm/output.c [hunk 1]
```diff
@@ -541,26 +549,24 @@ static void checksectionoverflow(uint32_t delta_size)
...
+			fatalerror("Couldn't write file '%s'\n", tzObjectname);
 
-	f = fopen(tzObjectname, "wb");
-	if (f == NULL)
-		fatalerror("Couldn't write file '%s'\n", tzObjectname);
-
-	struct PatchSymbol *pSym;
-	struct Section *pSect;
+		fwrite(RGBDS_OBJECT_VERSION_STRING, 1,
+		strlen(RGBDS_OBJECT_VERSION_STRING), f);
```
Comment (dbrotz) [inline src/asm/output.c]: Could you indent the arguments so that they don't line up with `fwrite`?

**Comment by ISSOtm** [comment]
I have been thinking about the same maintainability problem and have considered using wrapper functions, however, some of the functions called are stdio functions, so we'd have to write our own, and I was somewhat reluctant to do that. Maybe it is a better idea to switch to those, I'm unsure.

File: src/asm/output.c (hunk 1 above)
Comment (ISSOtm) [reply src/asm/output.c]: Yes, my bad.

**Comment by dbrotz** [comment]
Another possibility would be to avoid doing anything other file output in `out_WriteObject()` or anything called by it. The error check in `writesymbol()` could be moved to a separate pass.

**Comment by ISSOtm** [comment]
Actually, that sounds like a good idea!
