### PR TITLE
Remove undefined behavior from shifts

### LINKED ISSUE #431: Shifts trigger undefined behavior
Reference for all statements below: https://en.cppreference.com/w/c/language/operator_arithmetic#Shift_operators

## The problem

RGBDS transparently uses C's `<<` and `>>` operators; however, these operators have plenty of undefined cases, which should be handled consistently.

The rationale behind C's undefined behavior is ensuring fast processing independently from the platform; however, we want RGBDS-produced code to be consistent across platforms, especially since [the](https://github.com/pret/pokered) [disassemblies](https://github.com/pret/pokeyellow) [are](https://github.com/pret/pokecrystal) [a](https://github.com/pret/poketcg) [thing](https://github.com/pret/pokepinball). Therefore, we should use custom operators that do not exhibit such undefined behavior.

### Large shift amounts

> In any case, the behavior is undefined if `rhs` is negative or is greater or equal the number of bits in the promoted `lhs`. 

**Trigger cases:** RGBDS uses `int32_t` as its main "value" type, so unless compiled on a platform with 64-bit or larger `int`, shift amounts greater **or equal to** 32 are UB. Negative amounts obviously are as well.

**Current behavior:** If an expression is evaluated by RGBASM, it causes a fatal error:
https://github.com/rednex/rgbds/blob/ccc666c1e4b38fa2d1608b81d49b0dac253cefca/src/asm/constexpr.c#L177-L182
But the linker doesn't care:
https://github.com/rednex/rgbds/blob/ccc666c1e4b38fa2d1608b81d49b0dac253cefca/src/link/patch.c#L185-L192

**Proposed fixes:**
- Shift amounts larger than 32 should be clamped to 32
- Shifts by 32 should act as a shift by 31 followed by a shift by 1 to keep with user expectations
- What about negative shifts? @pinobatch voiced that they would expect this to flip the shift direction, but if that's not the current behavior we might break code that relies on it

### Right shifts of negative value

> For negative `LHS`, the value of `LHS >> RHS` is implementation-defined [...]

[GCC's behavior](https://gcc.gnu.org/onlinedocs/gcc/Integers-implementation.html#Integers-implementation):
> Signed ‘>>’ acts on negative numbers by sign extension.

I'm unable to find Clang's documentation of their implementation, however.

**Trigger cases:** Go figure, since there are no warnings. Probably some macros that shift bitfields?

**Current behavior:** Ignored, thus left to the compiler's implementation.

**Proposed fix:** Keep sign extension, but make it explicit for portability & future-proofing.

### Left shifts of negative value

I haven't found anything in the linked document about left shifts of negative values, only positive.

**Trigger cases:** [This](https://travis-ci.org/rednex/rgbds/jobs/582889877#L5376) and more.

**Current behavior:** Not sure, beyond a warning.
https://github.com/rednex/rgbds/blob/ccc666c1e4b38fa2d1608b81d49b0dac253cefca/src/asm/constexpr.c#L173-L175

**Proposed fix:**
- Either keep current behavior, if it's critical, or
- Use bitwise shifting, since arithmetic shifting can be achieved through multiplication by a power of 2

### PR DESCRIPTION
**Pull request by ISSOtm**
Fixes #431.
`asl` and `asr` functions in `src/link/patch.c` courtesy of @PinoBatch.
(Reorganized that code in RGBASM evaluators to sprinkle warnings)

### CODE REVIEW

File: src/asm/constexpr.c [hunk 1]
```diff
@@ -209,28 +209,53 @@ void constexpr_BinaryOp(struct ConstExpression *expr,
...
 			if (value2 < 0)
-				fatalerror("Shift by negative value: %d",
-					   value2);
-			else if (value2 >= 32)
-				fatalerror("Shift by too big value: %d",
-					   value2);
+				warning(WARNING_SHIFT_AMOUNT, "Shifting right by negative amount %d",
+					value2);
+			value2 = -value2; // Treat right shift as negative left
+shift:
```
Comment (AntonioND) [inline src/asm/constexpr.c]: Let's avoid gotos... I think this should be a function.

Comment (ISSOtm) [reply src/asm/constexpr.c]: I agree, but it seemed too specific at the time. Such a simple `goto` seemed like it wouldn't hurt, and also preserves locality/context.

**Comment by aaaaaa123456789** [comment]
As I've said in other places, the warning for shifting negative values seems like a bad idea. This is a very well-defined operation with a very well-defined result, and having to litter code with often-hard-to-calculate bit-clearing constants doesn't help anyone.  
(Anyone who thinks that `((\1) & ((1 << (-(\2) & 31)) - 1)) << (\2)` is clearer than `(\1) << (\2)` feel free to correct me; I had to stop to count the parens in that first expression like four times before getting them right.)

File: src/asm/constexpr.c (hunk 1 above)
Comment (aaaaaa123456789) [reply src/asm/constexpr.c]: Very much harm has been done by the widespread myth that `goto` is inherently wrong. People might argue that non-linear flow is complicated, but every single flow control keyword introduces non-linear code flow and that has (fortunately) never stopped anyone from using them.

The reason why people spoke loudly against `goto` half a century ago was because, with many programmers being used to assembly and to the idea of creating control structures by jumping around, people used `goto` instead of the proper flow control keywords that higher-level languages introduced. This remains a valid complaint, but _nobody does that nowadays_. There's no reason to avoid using `goto` when you really do want to have multiple code paths concur at a point; it's the natural way to do it.

All in all, while people have been historically right when complaining about others using `goto` to reinvent the `while` loop, that's not what people use it for nowadays, and therefore there's no reason to treat it as an evil thing that should not be touched.

Comment (AntonioND) [reply src/asm/constexpr.c]: IN general, ``goto`` is the wrong thing to do. It has some nice uses like returning from a function with several error conditions that also needs to allocate resources:
```
int main(void)
{
    int ret;

    void *p = malloc(100);

    if (function1() == ERROR) {
        ret = -1;
        goto cleanup;
    }

    if (function2() == ERROR) {
        ret = -2;
        goto cleanup;
    }
        
    ret = 0;
cleanup:
    free(p);
    return ret;
}
```
In other situation, if you are forced to use ``goto``, it is because the code flow is a mess. If not, for the most part, you don't need it.

**Comment by ISSOtm** [comment]
Removed the `goto`, though I like this solution less because it duplicates the `shr` check.
Removed the warning when left shifting negative values. That said, again, you could just have disabled the warning if you didn't care about it.
